version: '3.8'

services:
  dopcast:
    build: .
    container_name: dopcast
    ports:
      - "8000:8000"  # API port
      - "8501:8501"  # Web UI port
    volumes:
      - ./content:/app/content
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: uv run main.py full

  # Optional Redis for caching and message queue
  redis:
    image: redis:alpine
    container_name: dopcast_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
